import sys

if sys.version_info[:2] >= (3, 8):
    # TODO: Import directly (no need for conditional) when
    # `python_requires = >= 3.8`
    from importlib.metadata import (
        PackageNotFoundError,
        version,
    )  # pragma: no cover
else:
    from importlib_metadata import (
        PackageNotFoundError,
        version,
    )  # pragma: no cover

try:
    # Change here if project is renamed and does not equal the package name
    dist_name = __name__
    __version__ = version(dist_name)
except PackageNotFoundError:  # pragma: no cover
    __version__ = "unknown"
finally:
    del version, PackageNotFoundError


# custom code not generated by PyScaffold
__all__ = [
    "metrics",
    "scaling",
    "temporal_matching",
    "timedate",
    "time_series",
    "grid",
    "colormaps",
]

import os

src_path = os.path.join(os.path.dirname(__file__), '..')

tests_path = os.path.join(src_path, '..', 'tests')
if not os.path.exists(tests_path):
    tests_path = 'unknown'

testdata_path = os.path.join(src_path, '..', 'tests', 'test-data')
if not os.path.exists(testdata_path):
    testdata_path = 'unknown'
