version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - pdf

submodules:
  include: all

python:
  version: 3.7
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
